apiVersion: v1
kind: Service
metadata:
  labels:
    app: acidonpe-dns
  name: acidonpe-dns
spec:
  ports:
    - name: tcp-5353
      protocol: TCP
      port: 5353
      targetPort: 53
    - name: udp-5353
      protocol: UDP
      port: 5353
      targetPort: 53
  selector:
    app: acidonpe-dns

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: acidonpe-dns
  name: acidonpe-dns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acidonpe-dns
  template:
    metadata:
      labels:
        name: acidonpe-dns
        app: acidonpe-dns
    spec:
      containers:
      - image: quay.io/acidonpe/bind9:acidonpe
        command: ["/bin/bash"]
        args: ["-c", "/etc/init.d/bind9 start && while true; do echo hello; sleep 10; done"]
        imagePullPolicy: Always
        name: acidonpe-dns
        ports:
          - containerPort: 53
            protocol: TCP
        resources: {}
        env:
          - name: APP_REF_NAME
            value: jump-app
      
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: acidonpe-dns-test
  name: acidonpe-dns-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acidonpe-dns-test
  template:
    metadata:
      labels:
        name: acidonpe-dns-test
        app: acidonpe-dns-test
    spec:
      containers:
      - image: sequenceiq/alpine-dig
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo hello; sleep 10; done"]
        name: acidonpe-dns-test
        resources: {}
        env:
          - name: APP_REF_NAME
            value: jump-app